### ISSUE TITLE
[Bug]: 更新 waylib 后 xwayland 崩溃

### ISSUE THREAD

**Issue by wineee** [linuxdeepin/treeland#309]
### SUMMARY | 问题概要

https://github.com/linuxdeepin/treeland/pull/308 后 xwayland 崩溃， 但是 tinywl 仍然正常

### LAUNCH-WAY | 启动方式

unknown

### BACKEND | 启动后端

X11

### STEPS TO REPRODUCE | 复现步骤

DISPLAY=:1 QT_SCALE_FACTOR=2 qtcreator  -platform xcb

```
#8  0x00007ffff550324b in  () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#9  0x00007ffff550334b in  () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#10 0x00007ffff54b7e3f in qt_assert(char const*, char const*, int) ()
    at /lib/x86_64-linux-gnu/libQt6Core.so.6
#11 0x00007ffff54b7e9c in qt_assert_x(char const*, char const*, char const*, int) ()
    at /lib/x86_64-linux-gnu/libQt6Core.so.6
#12 0x00007ffff77e0a16 in Waylib::Server::WObject::waylandClient() const (this=0x5555562e4f20)
    at /home/rewine/treeland/waylib/src/server/kernel/wglobal.cpp:26
#13 0x00007ffff7874adf in Waylib::Server::WQuickSocket::qmlAttachedProperties(QObject*)
    (target=0x5555562e4f10)
    at /home/rewine/treeland/waylib/src/server/qtquick/private/wquicksocket.cpp:36
#14 0x00007ffff665f5e2 in qmlAttachedPropertiesObject(QObject*, QObject* (*)(QObject*), bool) ()
    at /lib/x86_64-linux-gnu/libQt6Qml.so.6
#15 0x00007ffff6770e35 in QV4::QQmlTypeWrapper::virtualGet(QV4::Managed const*, QV4::PropertyKey, QV4::Value const*, bool*) () at /lib/x86_64-linux-gnu/libQt6Qml.so.6                                              
#16 0x00007ffff65b9fb4 in QV4::Lookup::getterFallback(QV4::Lookup*, QV4::ExecutionEngine*, QV4::Value const&) () at /lib/x86_64-linux-gnu/libQt6Qml.so.6                                                            
#17 0x00007ffff676f2d0 in QV4::QQmlTypeWrapper::virtualResolveLookupGetter(QV4::Object const*, QV4::ExecutionEngine*, QV4::Lookup*) () at /lib/x86_64-linux-gnu/libQt6Qml.so.6                                      
#18 0x00007ffff662ce6c in  () at /lib/x86_64-linux-gnu/libQt6Qml.so.6
#19 0x00007ffff662f3da in  () at /lib/x86_64-linux-gnu/libQt6Qml.so.6
#20 0x00007ffff65a4bfe in  () at /lib/x86_64-linux-gnu/libQt6Qml.so.6

```

**Comment by Groveer** [comment]
Xwayland 崩溃问题已解决，关闭此issue，see https://github.com/linuxdeepin/treeland/pull/319
