### ISSUE TITLE
[Bug]:  (YaoBing Xiao) 2024-12-11 15:37:44 crash-1223

### ISSUE THREAD

**Issue by lbwtw** [linuxdeepin/treeland#360]
```shell
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/treeland treeland --lockscreen --socket /tmp/ddm--lnIrsq'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44

warning: 44     ./nptl/pthread_kill.c: 没有那个文件或目录
[Current thread is 1 (Thread 0x7f25b6fdb580 (LWP 1223))]
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
linuxdeepin/treeland.private#1  0x00007f25bbaa715f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
linuxdeepin/treeland.private#2  0x00007f25bba59102 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
linuxdeepin/treeland.private#3  0x00007f25bba424f2 in __GI_abort () at ./stdlib/abort.c:79
linuxdeepin/treeland.private#4  0x00007f25ba44a22f in ??? () at /lib/x86_64-linux-gnu/libdtk6log.so.0
linuxdeepin/treeland.private#5  0x00007f25ba44d428 in ??? () at /lib/x86_64-linux-gnu/libdtk6log.so.0
linuxdeepin/treeland.private#6  0x00007f25bc0fef7b in ??? () at /usr/bin/../lib/x86_64-linux-gnu/libQt6Core.so.6
linuxdeepin/treeland.private#7  0x00007f25bc0f7eab in ??? () at /usr/bin/../lib/x86_64-linux-gnu/libQt6Core.so.6
linuxdeepin/treeland.private#8  0x00007f25bc0bc415 in QMessageLogger::fatal(char const*, ...) const () at /usr/bin/../lib/x86_64-linux-gnu/libQt6Core.so.6
linuxdeepin/treeland.private#9  0x00007f25bc0bc48f in qt_assert(char const*, char const*, int) () at /usr/bin/../lib/x86_64-linux-gnu/libQt6Core.so.6
linuxdeepin/treeland.private#10 0x00007f25bd615a22 in Waylib::Server::WObject::waylandClient (this=0x560b085e6650) at /home/v25/Documents/Code/waylib/src/server/kernel/wglobal.cpp:27
linuxdeepin/treeland.private#11 0x00007f25bdd1b4a9 in SurfaceWrapper::SurfaceWrapper
    (this=0x560b089dfa20, qmlEngine=0x560b068d6000, shellSurface=0x560b085e6640, type=SurfaceWrapper::Type::XdgPopup, parent=0x0, isProxy=false)
    at /home/v25/Documents/Code/treeland.private/src/core/surfacewrapper.cpp:146
linuxdeepin/treeland.private#12 0x00007f25bdd31046 in ShellHandler::onXdgPopupSurfaceAdded (this=0x560b0693b0c0, surface=0x560b085e6640)
    at /home/v25/Documents/Code/treeland.private/src/core/shellhandler.cpp:179
linuxdeepin/treeland.private#13 0x00007f25bdd39af5 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<Waylib::Server::WXdgPopupSurface*>, void, void (ShellHandler::*)(Waylib::Server::WXdgPopupSurface*)>::call(void (ShellHandler::*)(Waylib::Server::WXdgPopupSurface*), ShellHandler*, void**)::{lambda()#1}::operator()() const                          
    (__closure=0x7ffcd8b2e3f0) at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:152
linuxdeepin/treeland.private#14 0x00007f25bdd3a5cf in QtPrivate::FunctorCallBase::call_internal<void, QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<Waylib::Server::WXdgPopupSurface*>, void, void (ShellHandler::*)(Waylib::Server::WXdgPopupSurface*)>::call(void (ShellHandler::*)(Waylib::Server::WXdgPopupSurface*), ShellHandler*, void**)::{lambda()#1}>(void**, QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<Waylib::Server::WXdgPopupSurface*>, void, void (ShellHandler::*)(Waylib::Server::WXdgPopupSurface*)>::call(void (ShellHandler::*)(Waylib::Server::WXdgPopupSurface*), ShellHandler*, void**)::{lambda()#1}&&) (args=0x7ffcd8b2e5a0, fn=...)                           
    at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:65
linuxdeepin/treeland.private#15 0x00007f25bdd39b56 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<Waylib::Server::WXdgPopupSurface*>, void, void (ShellHandler::*)(Waylib::Server::WXdgPopupSurface*)>::call                                                                                                                                              
    (f=(void (ShellHandler::*)(class ShellHandler * const, class Waylib::Server::WXdgPopupSurface *)) 0x7f25bdd30fee <ShellHandler::onXdgPopupSurfaceAdded(Waylib::Server::WXdgPopupSurface*)>, o=0x560b0693b0c0, arg=0x7ffcd8b2e5a0) at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:151
linuxdeepin/treeland.private#16 0x00007f25bdd38d54 in QtPrivate::FunctionPointer<void (ShellHandler::*)(Waylib::Server::WXdgPopupSurface*)>::call<QtPrivate::List<Waylib::Server::WXdgPopupSurface*>, void>                                                                                                                                                                     
    (f=(void (ShellHandler::*)(class ShellHandler * const, class Waylib::Server::WXdgPopupSurface *)) 0x7f25bdd30fee <ShellHandler::onXdgPopupSurfaceAdded(Waylib::Server::WXdgPopupSurface*)>, o=0x560b0693b0c0, arg=0x7ffcd8b2e5a0) at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:199
linuxdeepin/treeland.private#17 0x00007f25bdd37e37 in QtPrivate::QCallableObject<void (ShellHandler::*)(Waylib::Server::WXdgPopupSurface*), QtPrivate::List<Waylib::Server::WXdgPopupSurface*>, void>:--Type <RET> for more, q to quit, c to continue without paging--                                                                                                          
:impl (which=1, this_=0x560b061fac30, r=0x560b0693b0c0, a=0x7ffcd8b2e5a0, ret=0x0) at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:570                     
linuxdeepin/treeland.private#18 0x00007f25bc1a596c in ??? () at /usr/bin/../lib/x86_64-linux-gnu/libQt6Core.so.6
linuxdeepin/treeland.private#19 0x00007f25bd5a9d29 in Waylib::Server::WXdgShell::popupSurfaceAdded (this=0x560b061dc300, _t1=0x560b085e6640)
    at /home/v25/Documents/Code/waylib/builddir/src/server/waylibserver_autogen/QEXRLBDUJQ/moc_wxdgshell.cpp:203
linuxdeepin/treeland.private#20 0x00007f25bd6f8be1 in Waylib::Server::WXdgShellPrivate::onNewXdgPopupSurface (this=0x560b06268cf0, popup=0x560b08a3f8b0)
    at /home/v25/Documents/Code/waylib/src/server/protocols/wxdgshell.cpp:80
linuxdeepin/treeland.private#21 0x00007f25bd6f8e86 in Waylib::Server::WXdgShell::initializeNewXdgPopupSurface (this=0x560b061dc300, popup=0x560b08549430)
    at /home/v25/Documents/Code/waylib/src/server/protocols/wxdgshell.cpp:114
linuxdeepin/treeland.private#22 0x00007f25bd723483 in operator() (__closure=0x560b086aa9c0, popup=0x560b08549430) at /home/v25/Documents/Code/waylib/src/server/protocols/wlayershell.cpp:55
linuxdeepin/treeland.private#23 0x00007f25bd724379 in operator() (__closure=0x7ffcd8b2e770) at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:141
linuxdeepin/treeland.private#24 0x00007f25bd724496 in QtPrivate::FunctorCallBase::call_internal<void, QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<wlr_xdg_popup*>, void, Waylib::Server::WLayerShellPrivate::onNewSurface(qw_layer_surface_v1*)::<lambda(wlr_xdg_popup*)> >::call(Waylib::Server::WLayerShellPrivate::onNewSurface(qw_layer_surface_v1*)::<lambda(wlr_xdg_popup*)>&, void**)::<lambda()> >(void **, struct {...} &&) (args=0x7ffcd8b2e900, fn=...)                                                                  
    at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:65
linuxdeepin/treeland.private#25 0x00007f25bd7243af in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<wlr_xdg_popup*>, void, Waylib::Server::WLayerShellPrivate::onNewSurface(qw_layer_surface_v1*)::<lambda(wlr_xdg_popup*)> >::call(struct {...} &, void **) (f=..., arg=0x7ffcd8b2e900) at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:140 
linuxdeepin/treeland.private#26 0x00007f25bd7242d3 in QtPrivate::FunctorCallable<Waylib::Server::WLayerShellPrivate::onNewSurface(qw_layer_surface_v1*)::<lambda(wlr_xdg_popup*)>, wlr_xdg_popup*>::call<QtPrivate::List<wlr_xdg_popup*>, void>(struct {...} &, void *, void **) (f=..., arg=0x7ffcd8b2e900) at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:362 
linuxdeepin/treeland.private#27 0x00007f25bd724140 in QtPrivate::QCallableObject<Waylib::Server::WLayerShellPrivate::onNewSurface(qw_layer_surface_v1*)::<lambda(wlr_xdg_popup*)>, QtPrivate::List<wlr_xdg_popup*>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=1, this_=0x560b086aa9b0, r=0x560b061bb310, a=0x7ffcd8b2e900, ret=0x0)     
    at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:572
linuxdeepin/treeland.private#28 0x00007f25bc1a596c in ??? () at /usr/bin/../lib/x86_64-linux-gnu/libQt6Core.so.6
linuxdeepin/treeland.private#29 0x00007f25bd770269 in qw_layer_surface_v1::notify_new_popup (this=0x560b07fcb1e0, _t1=0x560b08549430)
    at /home/v25/Documents/Code/qwlroots/builddir/src/qwlroots_autogen/GZRP3O7STM/moc_qwlayershellv1.cpp:141
linuxdeepin/treeland.private#30 0x00007f25bdd05507 in qw_signal_connector::callSlot1 (wl_listener=0x560b06f11908, data=0x560b08549430) at /usr/include/qwlroots/qwsignalconnector.h:149
linuxdeepin/treeland.private#31 0x00007f25bc5a1afc in wl_signal_emit_mutable () at /usr/bin/../lib/x86_64-linux-gnu/libwayland-server.so.0
linuxdeepin/treeland.private#32 0x00007f25bd152b71 in layer_surface_handle_get_popup (client=0x560b0863b7b0, layer_resource=0x560b086aa110, popup_resource=0x560b0895ee60)
    at ../types/wlr_layer_shell_v1.c:256
linuxdeepin/treeland.private#33 0x00007f25b99e901a in ??? () at /lib/x86_64-linux-gnu/libffi.so.8
linuxdeepin/treeland.private#34 0x00007f25b99e84be in ??? () at /lib/x86_64-linux-gnu/libffi.so.8
linuxdeepin/treeland.private#35 0x00007f25b99e8bad in ffi_call () at /lib/x86_64-linux-gnu/libffi.so.8
linuxdeepin/treeland.private#36 0x00007f25bc5a5f46 in ??? () at /usr/bin/../lib/x86_64-linux-gnu/libwayland-server.so.0
linuxdeepin/treeland.private#37 0x00007f25bc5a0c9a in ??? () at /usr/bin/../lib/x86_64-linux-gnu/libwayland-server.so.0
--Type <RET> for more, q to quit, c to continue without paging--
linuxdeepin/treeland.private#38 0x00007f25bc5a3c52 in wl_event_loop_dispatch () at /usr/bin/../lib/x86_64-linux-gnu/libwayland-server.so.0
linuxdeepin/treeland.private#39 0x00007f25bd605c36 in operator() (__closure=0x560b061fec60) at /home/v25/Documents/Code/waylib/src/server/kernel/wserver.cpp:108
linuxdeepin/treeland.private#40 0x00007f25bd6078cf in operator() (__closure=0x7ffcd8b2f0d0) at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:141
linuxdeepin/treeland.private#41 0x00007f25bd607980 in QtPrivate::FunctorCallBase::call_internal<void, QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, Waylib::Server::WServerPrivate::init()::<lambda()> >::call(Waylib::Server::WServerPrivate::init()::<lambda()>&, void**)::<lambda()> >(void **, struct {...} &&) (args=0x7ffcd8b2f260, fn=...)   
    at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:65
linuxdeepin/treeland.private#42 0x00007f25bd607905 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, Waylib::Server::WServerPrivate::init()::<lambda()> >::call(struct {...} &, void **) (f=..., arg=0x7ffcd8b2f260) at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:140                                                              
linuxdeepin/treeland.private#43 0x00007f25bd607879 in QtPrivate::FunctorCallable<Waylib::Server::WServerPrivate::init()::<lambda()> >::call<QtPrivate::List<>, void>(struct {...} &, void *, void **)
    (f=..., arg=0x7ffcd8b2f260) at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:362
linuxdeepin/treeland.private#44 0x00007f25bd607792 in QtPrivate::QCallableObject<Waylib::Server::WServerPrivate::init()::<lambda()>, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=1, this_=0x560b061fec50, r=0x560b0698cd70, a=0x7ffcd8b2f260, ret=0x0)                                                                 
    at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:572
linuxdeepin/treeland.private#45 0x00007f25bc1a596c in ??? () at /usr/bin/../lib/x86_64-linux-gnu/libQt6Core.so.6
linuxdeepin/treeland.private#46 0x00007f25bc1afe83 in QSocketNotifier::activated(QSocketDescriptor, QSocketNotifier::Type, QSocketNotifier::QPrivateSignal) ()
    at /usr/bin/../lib/x86_64-linux-gnu/libQt6Core.so.6
linuxdeepin/treeland.private#47 0x00007f25bc1affb3 in QSocketNotifier::event(QEvent*) () at /usr/bin/../lib/x86_64-linux-gnu/libQt6Core.so.6
linuxdeepin/treeland.private#48 0x00007f25bc159898 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/bin/../lib/x86_64-linux-gnu/libQt6Core.so.6
linuxdeepin/treeland.private#49 0x00007f25bc3554af in ??? () at /usr/bin/../lib/x86_64-linux-gnu/libQt6Core.so.6
linuxdeepin/treeland.private#50 0x00007f25ba1b5e0f in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
linuxdeepin/treeland.private#51 0x00007f25ba1b7e97 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
linuxdeepin/treeland.private#52 0x00007f25ba1b84b0 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
linuxdeepin/treeland.private#53 0x00007f25bc34cfd0 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/bin/../lib/x86_64-linux-gnu/libQt6Core.so.6
linuxdeepin/treeland.private#54 0x00007f25bc1625da in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/bin/../lib/x86_64-linux-gnu/libQt6Core.so.6
linuxdeepin/treeland.private#55 0x00007f25bc15c6c8 in QCoreApplication::exec() () at /usr/bin/../lib/x86_64-linux-gnu/libQt6Core.so.6
linuxdeepin/treeland.private#56 0x0000560adc0c166a in main (argc=5, argv=0x7ffcd8b2f8d8) at /home/v25/Documents/Code/treeland.private/src/main.cpp:46
(gdb) 
```

**Comment by wineee** [comment]
统一记录到： https://github.com/linuxdeepin/treeland/issues/360
